const ACTIONS = {
    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_ERROR: 'SIGN_IN_ERROR',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    SIGN_OUT: 'SIGN_OUT',
    POST_CANDIDATE_START:"POST_CANDIDATE_START",
    POST_CANDIDATE_SUCCESS:"POST_CANDIDATE_SUCCESS",
    POST_CANDIDATE_ERROR:"POST_CANDIDATE_ERROR",
}

export default ACTIONS;
